export const COPY = {
  en: {
    brand: 'Nytto Labs',
    product: 'Curl-to-Buy',
    kicker: 'Digital files. Dollar prices.',
    hero1: 'Post a file.',
    hero2: 'Get paid.',
    swish: 'Like Swish — but for files.',
    lede: 'Upload a PDF, video, preset — any file up to 100 MB you have the right to sell. Set a dollar price. Share the link. Buyers pay by card through Stripe. You keep 95%.',
    cta: 'Post a file',
    live: 'Live',
    chips: ['Cards only', '5% fee', 'No account', '100 MB'],
    samplePay: 'Buyer pays by card',
    sampleKeep: 'You keep',
    step1t: 'Upload',
    step1: 'Pick a file (up to 100 MB). PDF, video, preset — whatever you sell.',
    step2t: 'Price it in $',
    step2: 'You set the dollar price. Post the link anywhere.',
    step3t: 'Get paid',
    step3: 'Buyer pays by card. Money lands in Stripe. 5% platform fee.',
    footerPay: 'Cards only via Stripe',
    footerFee: '5% platform fee',
    footerPayout: 'Payouts via Nytto Labs',
    legal: 'Nytto Labs is operated by Fredrik Kornelind (Sweden). Approved for F-tax. VAT registered.',
    uploadTitle: 'Post a file',
    uploadSubtitle: 'Sell a digital product with one link.',
    uploadLede: 'Choose a file and set a one-time price in USD. Share the payment link anywhere. After payment, the buyer gets access to the download.',
    file: 'File',
    drop: 'Drop a digital file here, or tap to choose',
    dropHint: 'Up to 100 MB · PDF, TXT, ZIP, video, audio, images, presets, templates, spreadsheets and code.',
    sellListTitle: 'What can you sell?',
    sellList: [
      'E-books, guides and reports',
      'Templates, presets and design assets',
      'Videos, audio and digital artwork',
      'Spreadsheets, presentations and ZIP bundles',
      'Source code, scripts and project files',
      'Your own license key or access instructions saved in a TXT or PDF',
    ],
    sellListFoot: 'One payment unlocks one file. Only sell content you own or have permission to distribute.',
    sellListCodeNote: 'This service delivers the uploaded file as-is — it does not generate a unique code per purchase, and it does not handle subscriptions or activation on your own site. If you sell a code or key this way, every buyer of that link receives the same one.',
    price: 'Price (USD)',
    minHint: 'Minimum $1',
    create: 'Create payment link',
    creating: 'Uploading…',
    feeNote: 'A 5% platform fee is deducted at payout via Stripe. Cards only — no Klarna.',
    youKeep: 'You keep',
    copy: 'Copy link',
    copied: 'Copied',
    share: 'Share',
    test: 'Preview your link',
    shareHint: 'Share this link — buyers pay and download here.',
    another: 'Post another file',
    linkReady: 'Link ready',
    minErr: 'Price must be at least $1.',
    fileErr: 'Choose a file first.',
    sizeErr: 'File is too large (max 100 MB).',
    buyKicker: 'Digital file',
    buyTitle: 'Pay to download',
    pay: 'Pay',
    payCard: 'Pay by card',
    notFound: 'This link is not for sale.',
    back: 'Back',
    successKicker: 'Payment confirmed',
    success: 'Your file is ready.',
    download: 'Download file',
    once: 'This download works from this page.',
    verifying: 'Checking payment…',
    payFail: 'Payment has not been completed.',
    noAccount: 'No account on either side.',
    mail: 'support@nyttolabs.com',
    stripeDown: 'Stripe is not configured.',
    legalTerms: 'Terms',
    legalRefunds: 'Refunds',
    legalPrivacy: 'Privacy',
  },
  sv: {
    brand: 'Nytto Labs',
    product: 'Curl-to-Buy',
    kicker: 'Digitala filer. Pris i dollar.',
    hero1: 'Lägg upp en fil.',
    hero2: 'Få betalt.',
    swish: 'Som Swish — fast för filer.',
    lede: 'Ladda upp PDF, video, preset — valfri fil upp till 100 MB som du har rätt att sälja. Sätt ett pris i dollar. Dela länken. Köparen betalar med kort via Stripe. Du behåller 95%.',
    cta: 'Lägg upp en fil',
    live: 'Live',
    chips: ['Endast kort', '5% avgift', 'Inget konto', '100 MB'],
    samplePay: 'Köparen betalar med kort',
    sampleKeep: 'Du behåller',
    step1t: 'Ladda upp',
    step1: 'Välj en fil (upp till 100 MB). PDF, video, preset — det du säljer.',
    step2t: 'Prissätt i $',
    step2: 'Du sätter priset i dollar. Klistra länken var som helst.',
    step3t: 'Få betalt',
    step3: 'Köparen betalar med kort. Pengarna landar i Stripe. 5% plattformsavgift.',
    footerPay: 'Endast kort via Stripe',
    footerFee: '5% plattformsavgift',
    footerPayout: 'Utbetalning via Nytto Labs',
    legal: 'Nytto Labs drivs av Fredrik Kornelind (Sverige). Godkänd för F-skatt. Momsregistrerad.',
    uploadTitle: 'Lägg upp en fil',
    uploadSubtitle: 'Sälj en digital produkt med en enda länk.',
    uploadLede: 'Välj en fil och sätt ett engångspris i dollar. Dela betallänken var du vill. Efter betalning får köparen tillgång till nedladdningen.',
    file: 'Fil',
    drop: 'Släpp en digital fil här, eller tryck för att välja',
    dropHint: 'Upp till 100 MB · PDF, TXT, ZIP, video, ljud, bilder, presets, mallar, kalkylark och kod.',
    sellListTitle: 'Vad kan du sälja?',
    sellList: [
      'E-böcker, guider och rapporter',
      'Mallar, presets och designfiler',
      'Videor, ljud och digital konst',
      'Kalkylark, presentationer och ZIP-paket',
      'Källkod, skript och projektfiler',
      'Din egen licensnyckel eller åtkomstinstruktioner sparade i en TXT eller PDF',
    ],
    sellListFoot: 'En betalning låser upp en fil. Sälj bara innehåll du äger eller har tillstånd att sprida.',
    sellListCodeNote: 'Tjänsten levererar den uppladdade filen som den är — den genererar ingen unik kod per köp och hanterar inte abonnemang eller aktivering på din egen webbplats. Säljer du en kod eller nyckel på det här sättet får alla köpare av den länken samma kod.',
    price: 'Pris (USD)',
    minHint: 'Minst $1',
    create: 'Skapa betallänk',
    creating: 'Laddar upp…',
    feeNote: '5% plattformsavgift dras vid utbetalning via Stripe. Endast kort — inte Klarna.',
    youKeep: 'Du behåller',
    copy: 'Kopiera länk',
    copied: 'Kopierad',
    share: 'Dela',
    test: 'Förhandsgranska din länk',
    shareHint: 'Dela den här länken — köparen betalar och laddar ner här.',
    another: 'Lägg upp en till fil',
    linkReady: 'Länken är redo',
    minErr: 'Priset måste vara minst $1.',
    fileErr: 'Välj en fil först.',
    sizeErr: 'Filen är för stor (max 100 MB).',
    buyKicker: 'Digital fil',
    buyTitle: 'Betala för att ladda ner',
    pay: 'Betala',
    payCard: 'Betala med kort',
    notFound: 'Den här länken är inte till salu.',
    back: 'Tillbaka',
    successKicker: 'Betalning bekräftad',
    success: 'Filen är redo.',
    download: 'Ladda ner filen',
    once: 'Den här nedladdningen fungerar från den här sidan.',
    verifying: 'Kontrollerar betalning…',
    payFail: 'Betalningen är inte klar.',
    noAccount: 'Inget konto på någon sida.',
    mail: 'support@nyttolabs.com',
    stripeDown: 'Stripe är inte konfigurerad.',
    legalTerms: 'Villkor',
    legalRefunds: 'Återbetalning',
    legalPrivacy: 'Integritet',
  },
}

export function formatUsd(n) {
  const v = Number.isFinite(n) ? n : 0
  return v % 1 === 0 ? `$${v.toFixed(0)}` : `$${v.toFixed(2)}`
}

export function keepUsd(n) {
  return Math.round(n * (1 - 0.05) * 100) / 100
}
