export const COPY = {
  en: {
    brand: 'Nytto Labs',
    product: 'Curl-to-Buy',
    kicker: 'Digital files. Dollar prices.',
    hero1: 'Post a file.',
    hero2: 'Get paid.',
    swish: 'Like Swish — but for files.',
    lede: 'Upload a PDF, video, preset — any file or pack up to 100 MB you have the right to sell. Set a dollar price. Share the link. Buyers pay by card through Stripe. You keep 95%.',
    cta: 'Post a file',
    live: 'Live',
    chips: ['Cards only', '5% fee', 'No account', '100 MB'],
    samplePay: 'Buyer pays by card',
    sampleKeep: 'You keep',
    noAccount: 'No account on either side.',
    step1t: 'Upload',
    step1: 'Pick a file or build a pack (up to 100 MB total). PDF, video, preset — whatever you sell.',
    step2t: 'Price it in $',
    step2: 'You set the dollar price and optional purchase or download limits. Post the link anywhere.',
    step3t: 'Get paid',
    step3: 'Buyer pays by card. Money lands in Stripe. 5% platform fee.',
    footerPay: 'Cards only via Stripe',
    footerFee: '5% platform fee',
    footerPayout: 'Payouts via Nytto Labs',
    legal: 'Nytto Labs, Sweden. Approved for F-tax. VAT registered.',
    uploadTitle: 'Post a file',
    uploadSubtitle: 'Sell a digital product with one link.',
    uploadLede: 'Choose a file or pack and set a one-time price in USD. Share the payment link anywhere. After payment, the buyer gets access to the download.',
    file: 'File',
    files: 'Files or pack',
    drop: 'Tap to choose one or more files',
    dropHint: 'Up to 20 files · 100 MB total · PDF, TXT, ZIP, video, audio, images, presets, templates, spreadsheets and code.',
    oneFile: 'file',
    manyFiles: 'files',
    title: 'What are you selling?',
    titleHint: 'Example: Summer photo pack',
    sellListTitle: 'What can you sell?',
    sellList: [
      'E-books, guides and reports',
      'Templates, presets and design assets',
      'Videos, audio and digital artwork',
      'Spreadsheets, presentations and ZIP bundles',
      'Source code, scripts and project files',
      'Your own license key or access instructions saved in a TXT or PDF',
    ],
    sellListFoot: 'Only sell content you own or have permission to distribute.',
    sellListCodeNote: 'This service delivers the uploaded files as-is — it does not generate a unique code per purchase, and it does not handle subscriptions or activation on your own site. If you sell a code or key this way, every buyer of that link receives the same one.',
    price: 'Price (USD)',
    minHint: 'Minimum $5',
    create: 'Create payment link',
    creating: 'Uploading…',
    feeNote: 'A 5% platform fee is deducted at payout via Stripe. Cards only.',
    youKeep: 'You keep',
    buyerLimit: 'How many people can buy?',
    downloadLimit: 'Downloads per file, per buyer',
    unlimited: 'Unlimited',
    limitHint: 'The selling link may be shared, but every buyer must pay. Each paid buyer gets a separate download allowance.',
    ageConfirm: 'I am 18+ and have the right to sell these files. No illegal content or sexual content involving anyone under 18.',
    linkReady: 'Link ready',
    copy: 'Copy link',
    copied: 'Copied',
    share: 'Share',
    test: 'Preview your link',
    shareHint: 'Share this link anywhere — your page, a text, Discord. When someone pays, you get paid automatically.',
    another: 'Post another file',
    minErr: 'Price must be at least $5.',
    fileErr: 'Choose a file first.',
    fileCountErr: 'Choose no more than 20 files.',
    sizeErr: 'The pack is too large (max 100 MB).',
    packageUnavailable: 'File packs are temporarily unavailable.',
    confirmErr: 'Confirm that you are 18+ and own the files.',
    buyKicker: 'Digital file',
    buyTitle: 'Pay to download',
    pay: 'Pay',
    payCard: 'Pay by card',
    notFound: 'This link is not for sale.',
    back: 'Back',
    soldOut: 'Sold out',
    left: 'up for grabs',
    timeLeft: 'Time limit:',
    beFast: 'Be fast, or miss it.',
    offerExpired: 'This offer has expired',
    descriptionLabel: 'Description (optional)',
    descriptionHint: 'Tell the buyer what they get. Shown on the payment page.',
    timeLimitLabel: 'Time limit',
    timeNoLimit: 'No limit',
    time15m: '15 minutes',
    time1h: '1 hour',
    time6h: '6 hours',
    time24h: '24 hours',
    time3d: '3 days',
    quantityLabel: 'How many can buy?',
    quantityUnlimited: 'Unlimited',
    successKicker: 'Payment confirmed',
    success: 'Your files are ready.',
    download: 'Download',
    downloadsEach: 'downloads per file',
    unlimitedDownloads: 'Unlimited downloads from this paid page',
    once: 'This download works from this page.',
    verifying: 'Checking payment…',
    payFail: 'Payment has not been completed.',
    mail: 'support@nyttolabs.com',
    stripeDown: 'Stripe is not configured.',
    connectKicker: 'Payouts',
    connectTitle: 'Where should we send your money?',
    connectText: 'Add payout details once. No Curl-to-Buy account or password required.',
    email: 'Your email address',
    connectButton: 'Continue to Stripe',
    continueStripe: 'Continue Stripe setup',
    openingStripe: 'Opening Stripe…',
    checkingPayouts: 'Checking payout setup…',
    connectFine: 'One-time setup, handled entirely by Stripe. Card processing is included in the platform fee.',
    connectError: 'Could not open Stripe setup.',
    feeNoteDynamic: 'platform fee, paid out automatically.',
    recoverLink: 'Already connected on another device?',
    recoverTitle: 'Verify by email',
    recoverSendCode: 'Send code',
    recoverSending: 'Sending…',
    recoverSent: 'Check your email for a 6-digit code.',
    recoverVerify: 'Verify',
    recoverVerifying: 'Verifying…',
    recoverError: 'Could not send the code. Try again.',
    recoverInvalidCode: 'Incorrect or expired code.',
    recoverCancel: 'Cancel',
    legalTerms: 'Terms',
    legalRefunds: 'Refunds',
    legalPrivacy: 'Privacy',
  },
  sv: {
    brand: 'Nytto Labs',
    product: 'Curl-to-Buy',
    kicker: 'Digitala filer. Pris i dollar.',
    hero1: 'Lägg upp en fil.',
    hero2: 'Få betalt.',
    swish: 'Som Swish — fast för filer.',
    lede: 'Ladda upp PDF, video, preset — valfri fil eller paket upp till 100 MB som du har rätt att sälja. Sätt ett pris i dollar. Dela länken. Köparen betalar med kort via Stripe. Du behåller 95%.',
    cta: 'Lägg upp en fil',
    live: 'Live',
    chips: ['Endast kort', '5% avgift', 'Inget konto', '100 MB'],
    samplePay: 'Köparen betalar med kort',
    sampleKeep: 'Du behåller',
    noAccount: 'Inget konto på någon sida.',
    step1t: 'Ladda upp',
    step1: 'Välj en fil eller bygg ett paket (upp till 100 MB totalt). PDF, video, preset — det du säljer.',
    step2t: 'Prissätt i $',
    step2: 'Du sätter priset i dollar och valfria köp- eller nedladdningsgränser. Klistra länken var som helst.',
    step3t: 'Få betalt',
    step3: 'Köparen betalar med kort. Pengarna landar i Stripe. 5% plattformsavgift.',
    footerPay: 'Endast kort via Stripe',
    footerFee: '5% plattformsavgift',
    footerPayout: 'Utbetalning via Nytto Labs',
    legal: 'Nytto Labs, Sverige. Godkänd för F-skatt. Momsregistrerad.',
    uploadTitle: 'Lägg upp en fil',
    uploadSubtitle: 'Sälj en digital produkt med en enda länk.',
    uploadLede: 'Välj en fil eller ett paket och sätt ett engångspris i dollar. Dela betallänken var du vill. Efter betalning får köparen tillgång till nedladdningen.',
    file: 'Fil',
    files: 'Filer eller paket',
    drop: 'Tryck för att välja en eller flera filer',
    dropHint: 'Upp till 20 filer · totalt 100 MB · PDF, TXT, ZIP, video, ljud, bilder, presets, mallar, kalkylark och kod.',
    oneFile: 'fil',
    manyFiles: 'filer',
    title: 'Vad säljer du?',
    titleHint: 'Exempel: Bildpaket sommar',
    sellListTitle: 'Vad kan du sälja?',
    sellList: [
      'E-böcker, guider och rapporter',
      'Mallar, presets och designfiler',
      'Videor, ljud och digital konst',
      'Kalkylark, presentationer och ZIP-paket',
      'Källkod, skript och projektfiler',
      'Din egen licensnyckel eller åtkomstinstruktioner sparade i en TXT eller PDF',
    ],
    sellListFoot: 'Sälj bara innehåll du äger eller har tillstånd att sprida.',
    sellListCodeNote: 'Tjänsten levererar de uppladdade filerna som de är — den genererar ingen unik kod per köp och hanterar inte abonnemang eller aktivering på din egen webbplats. Säljer du en kod eller nyckel på det här sättet får alla köpare av den länken samma kod.',
    price: 'Pris (USD)',
    minHint: 'Minst $5',
    create: 'Skapa betallänk',
    creating: 'Laddar upp…',
    feeNote: '5% plattformsavgift dras vid utbetalning via Stripe. Endast kort.',
    youKeep: 'Du behåller',
    buyerLimit: 'Hur många får köpa?',
    downloadLimit: 'Nedladdningar per fil och köpare',
    unlimited: 'Obegränsat',
    limitHint: 'Säljlänken får delas, men varje köpare måste betala. Varje betalning får en egen nedladdningsgräns.',
    ageConfirm: 'Jag är 18+ och har rätt att sälja filerna. Inget olagligt innehåll eller sexuellt innehåll med någon under 18.',
    linkReady: 'Länken är redo',
    copy: 'Kopiera länk',
    copied: 'Kopierad',
    share: 'Dela',
    test: 'Förhandsgranska din länk',
    shareHint: 'Dela länken var du vill — din sida, ett sms, Discord. När någon betalar får du betalt automatiskt.',
    another: 'Lägg upp en till fil',
    minErr: 'Priset måste vara minst $5.',
    fileErr: 'Välj en fil först.',
    fileCountErr: 'Välj högst 20 filer.',
    sizeErr: 'Paketet är för stort (max 100 MB).',
    packageUnavailable: 'Filpaket är tillfälligt otillgängliga.',
    confirmErr: 'Bekräfta att du är 18+ och äger filerna.',
    buyKicker: 'Digital fil',
    buyTitle: 'Betala för att ladda ner',
    pay: 'Betala',
    payCard: 'Betala med kort',
    notFound: 'Den här länken är inte till salu.',
    back: 'Tillbaka',
    soldOut: 'Slutsåld',
    left: 'kvar att ta',
    timeLeft: 'Tidsgräns:',
    beFast: 'Var snabb, annars är den borta.',
    offerExpired: 'Erbjudandet har gått ut',
    descriptionLabel: 'Beskrivning (valfritt)',
    descriptionHint: 'Berätta vad köparen får. Visas på betalsidan.',
    timeLimitLabel: 'Tidsgräns',
    timeNoLimit: 'Ingen gräns',
    time15m: '15 minuter',
    time1h: '1 timme',
    time6h: '6 timmar',
    time24h: '24 timmar',
    time3d: '3 dagar',
    quantityLabel: 'Hur många får köpa?',
    quantityUnlimited: 'Obegränsat',
    successKicker: 'Betalning bekräftad',
    success: 'Dina filer är klara.',
    download: 'Ladda ner',
    downloadsEach: 'nedladdningar per fil',
    unlimitedDownloads: 'Obegränsade nedladdningar från den betalda sidan',
    once: 'Den här nedladdningen fungerar från den här sidan.',
    verifying: 'Kontrollerar betalning…',
    payFail: 'Betalningen är inte klar.',
    mail: 'support@nyttolabs.com',
    stripeDown: 'Stripe är inte konfigurerad.',
    connectKicker: 'Utbetalningar',
    connectTitle: 'Vart ska vi skicka dina pengar?',
    connectText: 'Lägg till utbetalningsuppgifter en gång. Inget Curl-to-Buy-konto eller lösenord krävs.',
    email: 'Din mejladress',
    connectButton: 'Fortsätt till Stripe',
    continueStripe: 'Fortsätt Stripe-inställningen',
    openingStripe: 'Öppnar Stripe…',
    checkingPayouts: 'Kontrollerar utbetalningar…',
    connectFine: 'Engångssetup som sköts helt av Stripe. Kortavgiften ingår i plattformsavgiften.',
    connectError: 'Kunde inte öppna Stripe-inställningen.',
    feeNoteDynamic: 'plattformsavgift, betalas ut automatiskt.',
    recoverLink: 'Redan uppkopplad på en annan enhet?',
    recoverTitle: 'Verifiera med mejl',
    recoverSendCode: 'Skicka kod',
    recoverSending: 'Skickar…',
    recoverSent: 'Kolla mejlen för en 6-siffrig kod.',
    recoverVerify: 'Verifiera',
    recoverVerifying: 'Verifierar…',
    recoverError: 'Kunde inte skicka koden. Försök igen.',
    recoverInvalidCode: 'Fel eller utgången kod.',
    recoverCancel: 'Avbryt',
    legalTerms: 'Villkor',
    legalRefunds: 'Återbetalning',
    legalPrivacy: 'Integritet',
  },
}

export function formatUsd(n) {
  const v = Number.isFinite(n) ? n : 0
  return v % 1 === 0 ? `$${v.toFixed(0)}` : `$${v.toFixed(2)}`
}

export function keepUsd(n) {
  return Math.round(n * 0.95 * 100) / 100
}
