export const COPY = {
  en: {
    brand: 'Nytto Labs',
    product: 'Curl-to-Buy',
    kicker: 'Digital files. Dollar prices.',
    hero1: 'Post a file.',
    hero2: 'Get paid.',
    swish: 'Like Swish — but for files.',
    lede: 'Upload a PDF, video, preset — any file up to 100 MB you have the right to sell. Set a dollar price. Share the link. Buyers pay by card through Stripe. You keep 95%.',
    cta: 'Post a file',
    live: 'Live',
    chips: ['Cards only', 'You keep 95%', 'Buyer needs no account', '100 MB'],
    samplePay: 'Buyer pays by card',
    sampleKeep: 'You keep',
    step1t: 'Upload',
    step1: 'Pick a file (up to 100 MB). PDF, video, preset — whatever you sell.',
    step2t: 'Price it in $',
    step2: 'You set the dollar price. Post the link anywhere.',
    step3t: 'Get paid',
    step3: 'Buyer pays by card. Money lands in Stripe. 5% platform fee.',
    footerPay: 'Cards only via Stripe',
    footerFee: '5% platform fee',
    footerPayout: 'Payouts via Nytto Labs',
    legal: 'Nytto Labs is operated by Fredrik Kornelind (Sweden). Approved for F-tax. VAT registered.',
    uploadTitle: 'Post a file',
    uploadLede: 'Choose the file and a dollar price. You get a link. The buyer pays by card and downloads straight away.',
    file: 'File',
    drop: 'Drop a file here, or tap to choose',
    dropHint: 'Up to 100 MB — PDF, video, preset. Files you have the right to sell.',
    price: 'Price (USD)',
    minHint: 'Minimum $1',
    create: 'Create payment link',
    creating: 'Uploading…',
    feeNote: 'A 5% platform fee is deducted at payout via Stripe. Cards only — no Klarna.',
    youKeep: 'You keep',
    copy: 'Copy link',
    copied: 'Copied',
    share: 'Share',
    test: 'Preview your link',
    shareHint: 'Share this link — buyers pay and download here.',
    another: 'Post another file',
    payoutTitle: 'Get paid — you keep 95%',
    payoutLede: 'Connect a payout account (Stripe) so buyers can pay you. Takes a minute. 5% platform fee.',
    payoutCta: 'Connect payouts',
    payoutChecking: 'Working…',
    payoutReady: '✓ Payouts connected — buyers can pay you.',
    payoutHint: 'Buyers can pay once you connect payouts above.',
    linkReady: 'Link ready',
    minErr: 'Price must be at least $1.',
    fileErr: 'Choose a file first.',
    sizeErr: 'File is too large (max 100 MB).',
    buyKicker: 'Digital file',
    buyTitle: 'Pay to download',
    pay: 'Pay',
    payCard: 'Pay by card',
    notFound: 'This link is not for sale.',
    back: 'Back',
    successKicker: 'Payment confirmed',
    success: 'Your file is ready.',
    download: 'Download file',
    once: 'This download works from this page.',
    verifying: 'Checking payment…',
    payFail: 'Payment has not been completed.',
    noAccount: 'Buyers need no account. Sellers connect Stripe to get paid.',
    mail: 'support@nyttolabs.com',
    stripeDown: 'Stripe is not configured.',
    legalTerms: 'Terms',
    legalRefunds: 'Refunds',
    legalPrivacy: 'Privacy',
    sellerKicker: 'Your payouts',
    sellerNoneTitle: 'No seller session found on this browser.',
    sellerNoneBody: 'Payouts are tied to the browser that connected them. Post a file and connect payouts from there, or open this page on the device you used originally.',
    sellerTitle: 'Payout status',
    sellerIncomplete: 'Onboarding isn’t finished yet.',
    sellerPayoutsPending: 'Charges are enabled, but Stripe hasn’t enabled payouts to your bank yet. This is usually automatic — check back soon.',
    sellerResume: 'Resume onboarding',
    sellerListings: 'Your files',
    sellerAutoNote: 'New files you post from this browser are linked to this payout account automatically.',
  },
  sv: {
    brand: 'Nytto Labs',
    product: 'Curl-to-Buy',
    kicker: 'Digitala filer. Pris i dollar.',
    hero1: 'Lägg upp en fil.',
    hero2: 'Få betalt.',
    swish: 'Som Swish — fast för filer.',
    lede: 'Ladda upp PDF, video, preset — valfri fil upp till 100 MB som du har rätt att sälja. Sätt ett pris i dollar. Dela länken. Köparen betalar med kort via Stripe. Du behåller 95%.',
    cta: 'Lägg upp en fil',
    live: 'Live',
    chips: ['Endast kort', 'Du behåller 95%', 'Köparen behöver inget konto', '100 MB'],
    samplePay: 'Köparen betalar med kort',
    sampleKeep: 'Du behåller',
    step1t: 'Ladda upp',
    step1: 'Välj en fil (upp till 100 MB). PDF, video, preset — det du säljer.',
    step2t: 'Prissätt i $',
    step2: 'Du sätter priset i dollar. Klistra länken var som helst.',
    step3t: 'Få betalt',
    step3: 'Köparen betalar med kort. Pengarna landar i Stripe. 5% plattformsavgift.',
    footerPay: 'Endast kort via Stripe',
    footerFee: '5% plattformsavgift',
    footerPayout: 'Utbetalning via Nytto Labs',
    legal: 'Nytto Labs drivs av Fredrik Kornelind (Sverige). Godkänd för F-skatt. Momsregistrerad.',
    uploadTitle: 'Lägg upp en fil',
    uploadLede: 'Välj fil och ett pris i dollar. Du får en länk. Köparen betalar med kort och laddar ner direkt.',
    file: 'Fil',
    drop: 'Släpp en fil här, eller tryck för att välja',
    dropHint: 'Upp till 100 MB — PDF, video, preset. Filer du har rätt att sälja.',
    price: 'Pris (USD)',
    minHint: 'Minst $1',
    create: 'Skapa betallänk',
    creating: 'Laddar upp…',
    feeNote: '5% plattformsavgift dras vid utbetalning via Stripe. Endast kort — inte Klarna.',
    youKeep: 'Du behåller',
    copy: 'Kopiera länk',
    copied: 'Kopierad',
    share: 'Dela',
    test: 'Förhandsgranska din länk',
    shareHint: 'Dela den här länken — köparen betalar och laddar ner här.',
    another: 'Lägg upp en till fil',
    payoutTitle: 'Få betalt — du behåller 95%',
    payoutLede: 'Koppla ett utbetalningskonto (Stripe) så köpare kan betala dig. Tar en minut. 5% plattformsavgift.',
    payoutCta: 'Koppla utbetalning',
    payoutChecking: 'Jobbar…',
    payoutReady: '✓ Utbetalning kopplad — köpare kan betala dig.',
    payoutHint: 'Köpare kan betala när du kopplat utbetalning ovan.',
    linkReady: 'Länken är redo',
    minErr: 'Priset måste vara minst $1.',
    fileErr: 'Välj en fil först.',
    sizeErr: 'Filen är för stor (max 100 MB).',
    buyKicker: 'Digital fil',
    buyTitle: 'Betala för att ladda ner',
    pay: 'Betala',
    payCard: 'Betala med kort',
    notFound: 'Den här länken är inte till salu.',
    back: 'Tillbaka',
    successKicker: 'Betalning bekräftad',
    success: 'Filen är redo.',
    download: 'Ladda ner filen',
    once: 'Den här nedladdningen fungerar från den här sidan.',
    verifying: 'Kontrollerar betalning…',
    payFail: 'Betalningen är inte klar.',
    noAccount: 'Köparen behöver inget konto. Säljaren kopplar Stripe för att få betalt.',
    mail: 'support@nyttolabs.com',
    stripeDown: 'Stripe är inte konfigurerad.',
    legalTerms: 'Villkor',
    legalRefunds: 'Återbetalning',
    legalPrivacy: 'Integritet',
    sellerKicker: 'Dina utbetalningar',
    sellerNoneTitle: 'Ingen säljarsession hittades i den här webbläsaren.',
    sellerNoneBody: 'Utbetalningar är kopplade till webbläsaren som kopplade dem. Lägg upp en fil och koppla utbetalning därifrån, eller öppna den här sidan på samma enhet som ursprungligen.',
    sellerTitle: 'Utbetalningsstatus',
    sellerIncomplete: 'Registreringen är inte klar än.',
    sellerPayoutsPending: 'Betalningar är aktiverade, men Stripe har inte aktiverat utbetalning till ditt bankkonto än. Det brukar gå automatiskt — kolla igen om en stund.',
    sellerResume: 'Fortsätt registreringen',
    sellerListings: 'Dina filer',
    sellerAutoNote: 'Nya filer du lägger upp från den här webbläsaren kopplas automatiskt till det här utbetalningskontot.',
  },
}

export function formatUsd(n) {
  const v = Number.isFinite(n) ? n : 0
  return v % 1 === 0 ? `$${v.toFixed(0)}` : `$${v.toFixed(2)}`
}

export function keepUsd(n) {
  return Math.round(n * (1 - 0.05) * 100) / 100
}
