import { FREE_FEE_BPS, FREE_MIN_SEK, FREE_MIN_USD, SUB_MIN_SEK, SUB_MIN_USD } from '../../lib/entitlement'
import { MAX_FILES, MAX_MB } from '../../lib/site'

// Prices and limits come from the same constants the server enforces.
const FEE = FREE_FEE_BPS / 100

export const LANDING = {
  en: {
    skip: 'Skip to content',
    nav: { how: 'How it works', pricing: 'Pricing', links: 'My links', create: 'Create your link', createShort: 'Create', home: 'Curl-to-Buy home', language: 'Language' },
    hero: {
      kicker: 'Payment links for files and things',
      title: ['Sell anything with one', 'link.'],
      lead: 'Upload a file or add an item, set a price and send the link. Your buyer pays right away and needs no Curl-to-Buy account.',
      primary: 'Create your link',
      secondary: 'See how it works',
      trust: ['Card payments by Stripe', 'Instant download', 'No monthly fee on free links'],
      stage: 'Illustration: a seller adds a preset pack, sets the price to $19, shares the link in a chat, and the buyer pays on the product page.',
      flow: ['Add it', 'Price it', 'Share it', 'Get paid'],
      link: 'pay.nyttolabs.com/dl/nordic-film', copied: 'Copied', paid: 'Paid', viaStripe: 'via Stripe',
      create: 'You create', share: 'You share', buy: 'They buy',
      newLink: 'New link', file: 'nordic-film-presets.zip', price: 'Price', makeLink: 'Create link',
      chat: 'Just released these. Link below.', delivered: 'Delivered',
      product: 'Nordic Film Presets', buyFor: 'Buy for', instant: 'Instant download',
    },
    demo: {
      kicker: 'See it in action',
      title: 'This is what your buyer sees.',
      lead: 'Pick an example. The page shows the product, the price and exactly what the buyer gets. The same card appears when you share the link.',
      tabs: 'Example products',
      page: 'Buy page',
      shared: 'When you share the link',
      chat: 'Just released these. Link below.',
      buyFor: 'Buy for',
      digital: 'Digital download',
      physical: 'Physical item',
      note: 'Example products for illustration.',
      examples: [
        { id: 'presets', tab: 'Presets', art: 'presets', kind: 'digital', name: 'Nordic Film Presets', price: '$19', meta: '2 files · ZIP, PDF · 24 MB', desc: 'Twelve film-look presets for Lightroom desktop and mobile, plus an install guide.', gets: ['Instant download right after payment', 'Secure card payment via Stripe', 'No account needed'] },
        { id: 'guide', tab: 'E-book', art: 'guide', kind: 'digital', name: 'Freelance Pricing Guide', price: '$12', meta: '1 file · PDF · 6 MB', desc: 'A 48-page guide to quoting, packaging and invoicing your freelance work.', gets: ['Instant download right after payment', 'Secure card payment via Stripe', 'No account needed'] },
        { id: 'print', tab: 'Print', art: 'print', kind: 'physical', name: 'Risograph Print, A3', price: '300 SEK', meta: 'New · Shipping included', desc: 'Two-colour riso print on 170 g paper, signed and shipped in a flat mailer.', gets: ['Secure card payment via Stripe', 'Ships to Sweden and Norway', 'Delivered in 3–5 days'] },
      ],
    },
    steps: {
      kicker: 'How it works',
      title: 'Three steps. One link.',
      items: [
        { name: 'Add it', body: 'A file, a bundle of files or a physical item. Add a cover image if you like.' },
        { name: 'Price it', body: 'Choose a price. Cap the number of sales or set a time window if you want.' },
        { name: 'Share it', body: 'Send the link anywhere. The buyer pays by card and you get paid through Stripe.' },
      ],
    },
    categories: {
      kicker: 'What you can sell',
      title: 'If it fits in a file or a parcel, it fits in a link.',
      cta: 'Start selling',
      items: [
        { art: 'files', name: 'Digital files', body: `Templates, audio, documents. Up to ${MAX_FILES} files and ${MAX_MB} MB per link.` },
        { art: 'photos', name: 'Photo packs', body: 'Full-resolution shoots, delivered straight to your client.' },
        { art: 'presets', name: 'Presets and templates', body: 'Lightroom presets, Notion and Figma templates, LUTs.' },
        { art: 'guide', name: 'E-books and guides', body: 'PDF guides, workbooks and checklists.' },
        { art: 'design', name: 'Design deliveries', body: 'Logos, brand kits and final files for clients.' },
        { art: 'print', name: 'Physical products', body: 'Prints, merch and handmade goods, with shipping in the price.' },
      ],
    },
    why: {
      kicker: 'Why Curl-to-Buy',
      title: 'Everything a sale needs. Nothing it doesn’t.',
      items: [
        { name: 'No web shop needed', body: 'One link replaces the store, the cart and the checkout page.' },
        { name: 'Buyers need no account', body: 'They open the link and pay by card. No sign-up, no password.' },
        { name: 'Instant delivery', body: 'Digital files are ready to download as soon as the payment goes through.' },
        { name: 'Bundles in one link', body: `Sell up to ${MAX_FILES} files together as one package.` },
        { name: 'Looks good when shared', body: 'Add a cover and your title, price and image appear in the link preview.' },
        { name: 'Payments by Stripe', body: 'Card payments go through Stripe, straight to your connected Stripe account.' },
        { name: 'You stay in control', body: 'Pause a link, cap the number of sales or set a time limit.' },
      ],
      seller: 'No Curl-to-Buy account for you either. You connect Stripe once with your email, and Stripe collects the details it needs.',
    },
    pricing: {
      kicker: 'Pricing',
      title: 'Simple pricing. No surprises.',
      free: { name: 'Free link', value: `${FEE}%`, unit: 'per sale to Curl-to-Buy', lines: [`Minimum price $${FREE_MIN_USD}`, 'No monthly fee', 'Digital files and physical items'] },
      sub: { name: 'Subscription', value: '0%', unit: 'platform fee', lines: [`Minimum price $${SUB_MIN_USD}`, 'Monthly plan'], link: 'See plans' },
      note: `Stripe’s card fee applies to every sale. Physical items are priced in SEK: at least ${FREE_MIN_SEK} SEK on free links and ${SUB_MIN_SEK} SEK for subscribers.`,
    },
    create: {
      kicker: 'Create your link',
      title: 'Ready when you are.',
      lead: 'Add your file or item, set the price and get your link. The first time, you connect Stripe so the money can reach you.',
      next: 'What happens next',
      steps: ['Connect Stripe once with your email.', 'Your link is ready to share right away.', 'Buyers pay by card. You get paid through Stripe.'],
      links: 'Manage links you already made',
      fee: `Free links: $${FREE_MIN_USD} minimum and ${FEE}% per sale. No monthly fee.`,
    },
    final: {
      title: 'Your next sale can start with one link.',
      button: 'Create your link',
      sub: `Free to start. ${FEE}% per sale on free links, no monthly fee.`,
    },
    footer: { tagline: 'Sell anything with one link.', subscriptions: 'Subscriptions', links: 'My links' },
  },
  sv: {
    skip: 'Hoppa till innehållet',
    nav: { how: 'Så funkar det', pricing: 'Pris', links: 'Mina länkar', create: 'Skapa din länk', createShort: 'Skapa', home: 'Curl-to-Buy startsida', language: 'Språk' },
    hero: {
      kicker: 'Betallänkar för filer och saker',
      title: ['Sälj med en enda', 'länk.'],
      lead: 'Ladda upp filen eller lägg till varan, sätt priset och skicka länken. Köparen betalar direkt och behöver inget Curl-to-Buy-konto.',
      primary: 'Skapa din länk',
      secondary: 'Se hur det fungerar',
      trust: ['Kortbetalning via Stripe', 'Direkt nedladdning', 'Ingen månadsavgift för gratislänkar'],
      stage: 'Illustration: en säljare lägger till ett presetpaket, sätter priset till 19 dollar, delar länken i en chatt och köparen betalar på produktsidan.',
      flow: ['Lägg till', 'Prissätt', 'Dela', 'Få betalt'],
      link: 'pay.nyttolabs.com/dl/nordic-film', copied: 'Kopierad', paid: 'Betalt', viaStripe: 'via Stripe',
      create: 'Du skapar', share: 'Du delar', buy: 'De köper',
      newLink: 'Ny länk', file: 'nordic-film-presets.zip', price: 'Pris', makeLink: 'Skapa länk',
      chat: 'Nu släppta. Länken här.', delivered: 'Levererat',
      product: 'Nordic Film Presets', buyFor: 'Köp för', instant: 'Direkt nedladdning',
    },
    demo: {
      kicker: 'Se det i praktiken',
      title: 'Så här ser köparen det.',
      lead: 'Välj ett exempel. Sidan visar produkten, priset och exakt vad köparen får. Samma kort syns när du delar länken.',
      tabs: 'Exempelprodukter',
      page: 'Köpsida',
      shared: 'När du delar länken',
      chat: 'Nu släppta. Länken här.',
      buyFor: 'Köp för',
      digital: 'Digital nedladdning',
      physical: 'Fysisk vara',
      note: 'Exempelprodukter för illustration.',
      examples: [
        { id: 'presets', tab: 'Presets', art: 'presets', kind: 'digital', name: 'Nordic Film Presets', price: '$19', meta: '2 filer · ZIP, PDF · 24 MB', desc: 'Tolv presets med filmkänsla för Lightroom på dator och mobil, plus en installationsguide.', gets: ['Direkt nedladdning efter betalning', 'Säker kortbetalning via Stripe', 'Inget konto behövs'] },
        { id: 'guide', tab: 'E-bok', art: 'guide', kind: 'digital', name: 'Prisguide för frilansare', price: '$12', meta: '1 fil · PDF · 6 MB', desc: 'En guide på 48 sidor om offerter, paketering och fakturering för frilansare.', gets: ['Direkt nedladdning efter betalning', 'Säker kortbetalning via Stripe', 'Inget konto behövs'] },
        { id: 'print', tab: 'Tryck', art: 'print', kind: 'physical', name: 'Risotryck, A3', price: '300 SEK', meta: 'Ny · Frakt ingår', desc: 'Tvåfärgstryck i riso på 170 g papper, signerat och skickat i platt kuvert.', gets: ['Säker kortbetalning via Stripe', 'Leverans till Sverige och Norge', 'Levereras inom 3–5 dagar'] },
      ],
    },
    steps: {
      kicker: 'Så funkar det',
      title: 'Tre steg. En länk.',
      items: [
        { name: 'Lägg till', body: 'En fil, ett paket med filer eller en fysisk vara. Lägg gärna till en omslagsbild.' },
        { name: 'Prissätt', body: 'Välj pris. Begränsa antalet köp eller sätt en tidsgräns om du vill.' },
        { name: 'Dela', body: 'Skicka länken var som helst. Köparen betalar med kort och du får betalt via Stripe.' },
      ],
    },
    categories: {
      kicker: 'Vad kan du sälja?',
      title: 'Ryms det i en fil eller ett paket, ryms det i en länk.',
      cta: 'Börja sälja',
      items: [
        { art: 'files', name: 'Digitala filer', body: `Mallar, ljud och dokument. Upp till ${MAX_FILES} filer och ${MAX_MB} MB per länk.` },
        { art: 'photos', name: 'Fotopaket', body: 'Hela fotograferingar i full upplösning, direkt till kunden.' },
        { art: 'presets', name: 'Presets och mallar', body: 'Lightroom-presets, Notion- och Figma-mallar, LUT:ar.' },
        { art: 'guide', name: 'E-böcker och guider', body: 'PDF-guider, arbetsböcker och checklistor.' },
        { art: 'design', name: 'Designleveranser', body: 'Logotyper, varumärkespaket och slutfiler till kunder.' },
        { art: 'print', name: 'Fysiska produkter', body: 'Tryck, merch och hantverk, med frakten inräknad i priset.' },
      ],
    },
    why: {
      kicker: 'Varför Curl-to-Buy',
      title: 'Allt en försäljning behöver. Inget mer.',
      items: [
        { name: 'Ingen webbshop behövs', body: 'En länk ersätter butiken, varukorgen och kassan.' },
        { name: 'Köparen behöver inget konto', body: 'Köparen öppnar länken och betalar med kort. Ingen registrering, inget lösenord.' },
        { name: 'Direkt leverans', body: 'Digitala filer går att ladda ner så fort betalningen är klar.' },
        { name: 'Paket i en länk', body: `Sälj upp till ${MAX_FILES} filer tillsammans som ett paket.` },
        { name: 'Snygg när den delas', body: 'Lägg till ett omslag så syns titel, pris och bild i länkförhandsvisningen.' },
        { name: 'Betalning via Stripe', body: 'Kortbetalningar går via Stripe direkt till ditt anslutna Stripe-konto.' },
        { name: 'Du har kontrollen', body: 'Pausa en länk, begränsa antalet köp eller sätt en tidsgräns.' },
      ],
      seller: 'Inget Curl-to-Buy-konto för dig heller. Du ansluter Stripe en gång med din e-post, och Stripe samlar in de uppgifter som behövs.',
    },
    pricing: {
      kicker: 'Pris',
      title: 'Enkelt pris. Inga överraskningar.',
      free: { name: 'Gratislänk', value: `${FEE} %`, unit: 'per försäljning till Curl-to-Buy', lines: [`Lägsta pris $${FREE_MIN_USD}`, 'Ingen månadsavgift', 'Digitala filer och fysiska varor'] },
      sub: { name: 'Abonnemang', value: '0 %', unit: 'plattformsavgift', lines: [`Lägsta pris $${SUB_MIN_USD}`, 'Månadsplan'], link: 'Se abonnemang' },
      note: `Stripes kortavgift tillkommer vid varje köp. Fysiska varor prissätts i kronor: minst ${FREE_MIN_SEK} kr för gratislänkar och ${SUB_MIN_SEK} kr för abonnenter.`,
    },
    create: {
      kicker: 'Skapa din länk',
      title: 'Redo när du är.',
      lead: 'Lägg till filen eller varan, sätt priset och få din länk. Första gången ansluter du Stripe så att pengarna kan nå dig.',
      next: 'Så här går det till',
      steps: ['Anslut Stripe en gång med din e-post.', 'Din länk går att dela direkt.', 'Köparen betalar med kort. Du får betalt via Stripe.'],
      links: 'Hantera länkar du redan har skapat',
      fee: `Gratislänkar: minst $${FREE_MIN_USD} och ${FEE} % per försäljning. Ingen månadsavgift.`,
    },
    final: {
      title: 'Din nästa försäljning kan börja med en länk.',
      button: 'Skapa din länk',
      sub: `Gratis att börja. ${FEE} % per försäljning på gratislänkar, ingen månadsavgift.`,
    },
    footer: { tagline: 'Sälj med en enda länk.', subscriptions: 'Abonnemang', links: 'Mina länkar' },
  },
}
